name: FRONTEND-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #Node(Dockerfile)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      #Dependencies
      - name: Install dependencies
        run: npm ci

      #TS Linter
      - name: Lint TypeScript
        run: npm run lint:ts

      #SCSS Linter
      - name: Lint SCSS
        run: npm run lint:scss

      #Vitest, Unit
      - name: Run unit tests
        run: npm run test:unit

      #Production build
      - name: Build project
        run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #Docker
      - name: Build Docker image
        run: docker build -t lango-frontend .
