name: client.yml
on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4

      - name: DEBUG stage
        run: |
          pwd
          ls -la
          echo "Current branch: ${GITHUB_REF}"  

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'


      #Dependencies
      - name: Install dependencies
        run: npm ci

      #TS Linter
      - name: Lint TypeScript
        run: npm run lint:ts

      #SCSS Linter
      - name: Lint SCSS
        run: npm run lint:scss

      #Vitest, Unit
      - name: Run unit tests
        run: npm run test:unit

      #Production build
      - name: Build project
        run: npm run build
